### ISSUE TITLE
Breaking Change: Superwall 2.1.0 Requires Early Initialization

### ISSUE THREAD

**Issue by OrcunJoyoLabs** [superwall/Superwall-Flutter#84]
### Environment

Flutter Superwall Kit version: Upgraded from 2.0.5 to 2.1.0

### Description

After upgrading from Flutter Superwall Kit 2.0.5 to 2.1.0, my iOS app fails to launch with the following error:

> SuperwallKit/Superwall.swift:217: Fatal error: Superwall has not been configured. Please call Superwall.configure() - at the very beginning of the app

Our application has this previously working initialization flow: Auth -> Purchase controller -> Superwall -> Other dependencies

This sequence worked properly in 2.0.5 but fails in 2.1.0 with the error above. This appears to be related to stricter initialization requirements in as moving the initialization to waaaaay earlier in the app launch does seem to work. However, this breaks my dependency chain as Superwall depends on Purchase Controller being initialized first, also introduces a risk with dependency chain in the app.

I have seen the release notes mention potentially breaking change - but I'm not sure if what I ran into is it. 

**Also I have confirmed that I'm not calling Superwall anywhere when it fails. It looks like the SDK is waiting for itself to be configured, then crashing the app when its not.** 

iOS App
### Podfile Before:

Superscript (0.1.18)
SuperwallKit (4.0.6): - Superscript (= 0.1.18)

### Podfile After:

Superscript (0.2.4)
SuperwallKit (4.3.0): - Superscript (= 0.2.4)

_Note that I only tried on iOS as we don't have an Android app_

**Comment by ianrumac** [comment]
Hey @OrcunJoyoLabs !

Thanks for the report - could you tell us what SDK methods are you accessing in the PurchaseController? Want to be able to reproduce this reliably.

This might be one of those possibly breaking changes, as we have completely reworked the SDK behind the publicly exposed interfaces. We'll investigate it ASAP 🙏

**Comment by OrcunJoyoLabs** [comment]
Thanks for response @ianrumac ! I just figured out what happened - Superwall.swift now expects configure to be called before accessing any shared functions.

I was previously accessing Superwall.shared.identify and Superwall.shared.setDelegate before configure during app startup when setting the user ID - which worked fine before!

Issue solved on my end, so feel free to close this. Would be great if you could be more vocal about these kinds of changes in the future since the exact same flow was supported previously!
